In [1]:
import os 
import pandas as pd
from natsort import natsorted
import re
fsldir=('/data/projects/istart-mid/derivatives/fsl')

In [2]:
'/data/projects/istart-mid/derivatives/fsl/sub-1001/L2_task-mid_model-2_type-ppi_seed-NAcc.gfeat/'

'/data/projects/istart-mid/derivatives/fsl/sub-1001/L2_task-mid_model-2_type-ppi_seed-NAcc.gfeat/'

In [9]:
subs=natsorted([d_name for d_name in os.listdir(fsldir) if d_name.startswith('sub') ])

cope_list=natsorted([re.search('(.*).feat',cope).group(1) for cope
                     in os.listdir(
    '/data/projects/istart-mid/derivatives/fsl/sub-1001/L2_task-mid_model-2_type-ppi_seed-NAcc.gfeat/')
                    if cope.startswith('cope')])
for cope in cope_list:
    oneR_subs=[]
    twoR_subs=[]
    for sub in subs:
        if [d_name for d_name in os.listdir(fsldir+'/%s'%(sub)) if d_name.startswith('L2')]:
            dataname='L2_task-mid_model-2_type-ppi_seed-NAcc.gfeat/%s.feat/stats/cope1.nii.gz'%(cope)
            if os.path.exists(fsldir+'/%s/%s'%(sub,dataname)):
                twoR_subs.append(fsldir+'/%s/%s'%(sub,dataname))
        else:
            dataname='L1_task-mid_model-2_type-ppi_seed-NAcc_run-1_sm-.feat/stats/%s.nii.gz'%(cope)
            if os.path.exists(fsldir+'/%s/%s'%(sub,dataname)):
                oneR_subs.append(fsldir+'/%s/%s'%(sub,dataname))
    fnames=natsorted(oneR_subs + twoR_subs)
    df=pd.DataFrame(data=fnames,columns=['fnames'])
    df.to_csv('/data/projects/istart-mid/code/L3_PPIdata_%s.tsv'%(cope),sep='\t',index=False)

In [10]:
subs

['sub-1001',
 'sub-1002',
 'sub-1003',
 'sub-1004',
 'sub-1006',
 'sub-1007',
 'sub-1009',
 'sub-1010',
 'sub-1011',
 'sub-1012',
 'sub-1016',
 'sub-1019',
 'sub-1021',
 'sub-1240',
 'sub-1242',
 'sub-1243',
 'sub-1244',
 'sub-1245',
 'sub-1247',
 'sub-1248',
 'sub-1249',
 'sub-1251',
 'sub-1253',
 'sub-1255',
 'sub-1276',
 'sub-1282',
 'sub-1285',
 'sub-1286',
 'sub-1294',
 'sub-1300',
 'sub-1301',
 'sub-1302',
 'sub-3101',
 'sub-3116',
 'sub-3122',
 'sub-3140',
 'sub-3143',
 'sub-3166',
 'sub-3173',
 'sub-3176',
 'sub-3186',
 'sub-3189',
 'sub-3190']

In [15]:
df=pd.read_csv('Reward_Sensitivity_newsubs.csv')
df['RealID']='sub-'+df['RealID'].astype(str)
df=df[df['RealID'].isin(subs)]
df['PC1_sqr']=df['PC1_de-meaned']**2
df['PC1_sqrDM']=df['PC1_sqr']-df['PC1_sqr'].mean()
df.head()
df[['Unnamed: 7','Mean_RSS','ABS_RSS']].to_csv('group_model_ev.tsv',index=False,sep='\t')

In [18]:
len(subs)

43

In [6]:
df.corr()

,Study,gender,SPSRWD,BISBAS_BAS,PC1,PC1_de-meaned,Unnamed: 7,SPSRWD_Z,BISBAS_Z,Mean_RSS,ABS_RSS
Study,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,NaN,1.000000,0.252058,-0.018770,0.087859,0.087859,NaN,0.252058,-0.018770,0.127482,0.111844
SPSRWD,NaN,0.252058,1.000000,0.674399,0.862251,0.862251,NaN,1.000000,0.674399,0.914986,0.161974
BISBAS_BAS,NaN,-0.018770,0.674399,1.000000,0.955471,0.955471,NaN,0.674399,1.000000,0.914986,0.164060
PC1,NaN,0.087859,0.862251,0.955471,1.000000,1.000000,NaN,0.862251,0.955471,0.993305,0.177269
PC1_de-meaned,NaN,0.087859,0.862251,0.955471,1.000000,1.000000,NaN,0.862251,0.955471,0.993305,0.177269
Unnamed: 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SPSRWD_Z,NaN,0.252058,1.000000,0.674399,0.862251,0.862251,NaN,1.000000,0.674399,0.914986,0.161974
BISBAS_Z,NaN,-0.018770,0.674399,1.000000,0.955471,0.955471,NaN,0.674399,1.000000,0.914986,0.164060
Mean_RSS,NaN,0.127482,0.914986,0.914986,0.993305,0.993305,NaN,0.914986,0.914986,1.000000,0.178163
ABS_RSS,NaN,0.111844,0.161974,0.164060,0.177269,0.177269,NaN,0.161974,0.164060,0.178163,1.000000